### ISSUE TITLE
サポートBot改良

### ISSUE THREAD

**Issue by ledlaggazi** [AzisabaCloud/support#1]
下記の追加機能を搭載して法務部処理・サポート全般の品質を向上させる
【サポート停止コマンド】…コマンド(ex./stop)を打ち込むと鯖民との通信が切れる。運営はサポートチャンネル内でその案件の処理方法を会議する。1案件(通報)1サポート制。わかりやすい。

【サポートチャンネル削除コマンド】…コマンド(ex./delete)を打ち込むとサポートチャンネルを削除する。手で消さないのは下にあるログ機能のため。

【ログ機能】…全てのサポートチャンネルでの会話を1チャンネルに転載する(コマンドによるサポートチャンネル削除時)。サポートチャンネルは案件が終了すると消されるので、誰を処罰したか、過去にどんな対応をしたか検索できるようにするため。あとで助かる。

【サポート開始時案内メッセージ変更】…1つの案件ごとに分けてサポートを送るように最初にメッセージを流す。

前:サポートを新たに開始しました！
後:サポートを新たに開始しました！サポート1回につき相談できる内容は1つまでです。処罰異議申し立ては1週間を過ぎた場合、一切対応しません。

【サポート終了時案内メッセージ変更】…終了時に案内メッセージを流す。

前:サポートが解決済みとマークされました。
　新しい報告を作成するには何かメッセージを送信してください。
後: サポートが解決済みとマークされました。通報の場合、証拠動画は1週間保管をお願いします。
　新しい報告を作成するには何かメッセージを送信してください。

そんな感じでよろしくお願いします🥺

**Comment by ledlaggazi** [comment]
追伸
【サポート開始】
サポートにDM
↓
DMメッセージ「サポートを新たに開始しました！サポート1回につき相談できる内容は1つまでです。処罰異議申し立ては1週間を過ぎた場合、一切対応しません。書き終えたらボタンを押してください。」
↓
書き終えたら押すボタンを表示
↓
書き終えてボタンを押す
↓
書き込み用、会議用を生成、内容をそれぞれに転載、書き込み用リンクを生成
↓
メッセージ「送信しました！下記のリンクを押してください。運営がBotを通じて対応します。これ以降はリンク先に書き込んでください。」
↓
同時にリンクを送信
↓
書き込み用チャンネルでBot経由の運営と会話

【サポート中】
運営は会議用で会議。通報者には会議は見えない。通報者と話すときは返信コマンドでBot経由で会話。

【サポート終了】
会議用をクローズ
↓
転載チャンネルに会議用の内容を転載
↓
書き込み用メッセージ「サポートが解決済みとマークされました。通報の場合、証拠動画は1週間保管をお願いします。この件について続報がある場合、続報ボタンを押してください。別件の場合は別件ボタンを押してください。」
↓
続報、別件ボタンを表示
↓
続報の場合、会議用を新規で立ち上げる。
別件の場合はDMに戻し、メッセージ「サポートを新たに開始しました！サポート1回につき相談できる内容は1つまでです。処罰異議申し立ては1週間を過ぎた場合、一切対応しません。書き終えたらボタンを押してください。」を表示してループ。
↓
会議用クローズ後、何もなく１週間経過すると書き込み用が削除される。

【返信コマンド】...会議用で会議中に通報者と会話する際に使用。コマンド(ex./r 本文)で書き込み用にBotが転載する

【クローズコマンド】...会議用にコマンド(ex./close)を打ち込むと会議用を削除して内容を転載チャンネルに転載。この時点から１週間で書き込み用削除。

【続報があった場合】...新規で会議用が作成され、頭に転載チャンネルのリンクを表示、続報を表示

【会議用削除～続報の処理】
会議用を削除し転載チャンネルに転載
↓
転載された最初のメッセージIDを転載IDとする
↓
会議用から書き込み用を取得
↓
書き込み用と転載IDを関連付ける、これはリスト化(複数登録)が可能
↓
続報が書き込み用にあった場合はリスト化された転載IDからメッセージIDを取得してジャンプリンクを生成
↓
続報の会議用チャンネルを生成する際にジャンプリンクを頭に表示

**Comment by YukiLeafX** [comment]
機能を分解して、簡潔にまとめる以下のようになる。

- チャンネルをコマンドで削除する
- チャンネルの会話ログを保存する
- 複数の案件に対応する
- ~異議申し立てに制限を設けてサポート開始時にメッセージを表示~
- 通報の場合に証拠を保存する旨のメッセージを表示

制限を設けるのはルールで変動する可能性があるのでサポートでは実装しない。

**Comment by YukiLeafX** [comment]
各機能のIssueを立てたのでクローズ
